FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY config/ ./config/
COPY database/ ./database/
COPY utils/ ./utils/
COPY web/ ./web/
#COPY xray/ ./xray/
#ENV PYTHONPATH=/app

RUN mkdir -p /app/data

#CMD ["python", "-m", "web.server"]
CMD ["uvicorn", "web.server:app", "--host", "0.0.0.0", "--port", "14888"]