version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DATABASE_URL=sqlite:////app/data/vpn_users.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - DATABASE_URL=sqlite:////app/data/vpn_users.db
    volumes:
      - ./data:/app/data
    ports:
      - "14888:14888"
    restart: unless-stopped